name: Windows - H2S - CM

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
  
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Bogyi2024/log/main/downloadcm.bat" -OutFile "downloadcm.bat"
          cmd /c downloadcm.bat
