name: Windows - H2S - XXX - 720 - DualSub

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
  
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Bogyi2024/log/main/directxxx720dual.bat" -OutFile "directxxx720dual.bat"
          cmd /c directxxx720dual.bat
